
//import static java.lang.String.format;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
//import java.util.Calendar.setTime;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Shivam
 */
public class hotelmanagement extends javax.swing.JFrame {

    private Object jtxtAddress;

    /**
     * Creates new form hotelmanagement
     */
    public hotelmanagement() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jTextField18 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jtxtFirst = new javax.swing.JTextField();
        jtxtLast = new javax.swing.JTextField();
        jtxtAddress1 = new javax.swing.JTextField();
        jtxtPostCode = new javax.swing.JTextField();
        jtxtCustMob = new javax.swing.JTextField();
        jtxtEmail = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        CheckIn = new javax.swing.JLabel();
        CheckOut = new javax.swing.JLabel();
        jtxtNationality = new javax.swing.JTextField();
        jtxtCustomerRef = new javax.swing.JTextField();
        RoomType = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLocaleChooser1 = new javax.swing.JComboBox<>();
        jtxtGender = new javax.swing.JComboBox<>();
        jtxtRoomType = new javax.swing.JComboBox<>();
        jtxtRoomNo = new javax.swing.JComboBox<>();
        jtxtRoomExtNo = new javax.swing.JComboBox<>();
        Meal = new javax.swing.JLabel();
        jcobMeal = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        JTable1 = new javax.swing.JTable();
        jtxtTotal = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jtxtTax = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jtxtSubTotal = new javax.swing.JTextField();
        Totalcost = new javax.swing.JButton();
        Update = new javax.swing.JButton();
        Delete = new javax.swing.JButton();
        Reset = new javax.swing.JButton();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jDateChooser2 = new com.toedter.calendar.JDateChooser();
        jDateChooser3 = new com.toedter.calendar.JDateChooser();
        Exit1 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        jLabel15.setText("jLabel15");

        jLabel16.setText("jLabel16");

        jLabel17.setText("jLabel17");

        jLabel18.setText("jLabel18");

        jLabel21.setText("jLabel21");

        jTextField18.setText("jTextField18");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel1.setText("Customer Ref");

        jLabel2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel2.setText("First Name");

        jLabel3.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel3.setText("Last Name");

        jLabel4.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel4.setText("Address 1");

        jLabel6.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel6.setText("Post Code");

        jLabel7.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel7.setText("Customer Mobile");

        jLabel8.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel8.setText("Email");

        jLabel9.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel9.setText("Nationality");

        jtxtFirst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtFirstActionPerformed(evt);
            }
        });

        jtxtLast.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtLastActionPerformed(evt);
            }
        });

        jtxtAddress1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtAddress1ActionPerformed(evt);
            }
        });

        jtxtPostCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtPostCodeActionPerformed(evt);
            }
        });

        jtxtCustMob.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtCustMobActionPerformed(evt);
            }
        });

        jtxtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtEmailActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setText("Date Of Birth");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setText("ID Type");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel12.setText("Gender");

        CheckIn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        CheckIn.setText("Check In Date");

        CheckOut.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        CheckOut.setText("Check Out Date");

        jtxtNationality.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtNationalityActionPerformed(evt);
            }
        });

        jtxtCustomerRef.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtCustomerRefActionPerformed(evt);
            }
        });

        RoomType.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        RoomType.setText("Room Type");

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel20.setText("Room No.");

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel22.setText("Room Ext No.");

        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1729, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 715, Short.MAX_VALUE)
        );

        jLocaleChooser1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLocaleChooser1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Id Type", "Driving Lic", "Passport", "Aadhar Card", "Student Id" }));

        jtxtGender.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jtxtGender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Gender", "Male", "Female", "Other" }));

        jtxtRoomType.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jtxtRoomType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Room Type", "Single", "Double", "Family" }));

        jtxtRoomNo.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jtxtRoomNo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "001", "002", "003", "004", "005", "006", "007", "008", "009", "010" }));

        jtxtRoomExtNo.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jtxtRoomExtNo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "001", "002", "003", "004", "005", "006", "007", "008", "009", "010" }));

        Meal.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Meal.setText("Meal:");

        jcobMeal.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jcobMeal.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Meal", "1 Item", "2 Item", "3 Item" }));

        JTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cust. ref", "First name", "Last name", "Address 1", "Post code", "Tel no.", "Email", "Nationality", "DOB", "Gender", "Check in date", "Check out date", "Meal", "Room type", "Room ext no."
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.String.class, java.lang.Object.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(JTable1);

        jtxtTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtTotalActionPerformed(evt);
            }
        });

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel23.setText("Tax");

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel24.setText("Sub Total");

        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel25.setText("Total");

        jtxtSubTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtSubTotalActionPerformed(evt);
            }
        });

        Totalcost.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        Totalcost.setText("Total cost");
        Totalcost.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TotalcostActionPerformed(evt);
            }
        });

        Update.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        Update.setText("update");
        Update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateActionPerformed(evt);
            }
        });

        Delete.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        Delete.setText("Delete");
        Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteActionPerformed(evt);
            }
        });

        Reset.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        Reset.setText("Reset");
        Reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResetActionPerformed(evt);
            }
        });

        Exit1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        Exit1.setText("Exit");
        Exit1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Exit1ActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jButton1.setText("Search");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(33, 33, 33)
                                .addComponent(jtxtCustMob))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(Meal)
                                            .addComponent(RoomType)
                                            .addComponent(jLabel20))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(jtxtRoomType, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jtxtRoomNo, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jcobMeal, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(0, 0, Short.MAX_VALUE)
                                                .addComponent(jLabel1)
                                                .addGap(42, 42, 42))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel2)
                                                    .addComponent(jLabel3))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(jtxtFirst, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE)
                                            .addComponent(jtxtLast, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jtxtCustomerRef)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel6))
                                        .addGap(61, 61, 61)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jtxtPostCode)
                                            .addComponent(jtxtAddress1)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel8)
                                            .addComponent(jLabel9))
                                        .addGap(60, 60, 60)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jtxtNationality)
                                            .addComponent(jtxtEmail)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel10)
                                            .addComponent(jLabel11)
                                            .addComponent(jLabel12)
                                            .addComponent(CheckIn)
                                            .addComponent(CheckOut))
                                        .addGap(23, 23, 23)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jtxtGender, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLocaleChooser1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jDateChooser1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jDateChooser3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jDateChooser2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel22)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jtxtRoomExtNo, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 7, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel24)
                                    .addComponent(jLabel25)
                                    .addComponent(jLabel23))
                                .addGap(29, 29, 29)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jtxtSubTotal)
                                    .addComponent(jtxtTotal)
                                    .addComponent(jtxtTax, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1074, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(313, 313, 313)
                        .addComponent(Totalcost, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Update)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Delete)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Reset, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Exit1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(788, 788, 788)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 566, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Delete, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Reset, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Totalcost, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Update, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Exit1, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jtxtCustomerRef, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jtxtFirst, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jtxtLast, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jtxtAddress1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel6)
                                    .addComponent(jtxtPostCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel7)
                                    .addComponent(jtxtCustMob, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel8)
                                    .addComponent(jtxtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel9)
                                    .addComponent(jtxtNationality, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel11)
                                    .addComponent(jLocaleChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jtxtGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel12))
                                .addGap(7, 7, 7)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(CheckIn, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jDateChooser2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(CheckOut)
                                    .addComponent(jDateChooser3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Meal)
                                    .addComponent(jcobMeal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(RoomType, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jtxtRoomType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel20)
                                    .addComponent(jtxtRoomNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jtxtRoomExtNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jtxtTax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(19, 19, 19)
                                        .addComponent(jtxtSubTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel24)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel25)
                                    .addComponent(jtxtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(421, 421, 421))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(286, 286, 286)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(701, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtxtFirstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtFirstActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtFirstActionPerformed

    private void jtxtLastActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtLastActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtLastActionPerformed

    private void jtxtAddress1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtAddress1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtAddress1ActionPerformed

    private void jtxtCustomerRefActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtCustomerRefActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtCustomerRefActionPerformed

    private void jtxtCustMobActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtCustMobActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtCustMobActionPerformed

    private void jtxtTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtTotalActionPerformed

    private void jtxtSubTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtSubTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtSubTotalActionPerformed

    private void DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteActionPerformed
      DefaultTableModel MOdel = (DefaultTableModel) JTable1.getModel();
if(JTable1.getSelectedRow()== -1){
    if(JTable1.getRowCount()== 0){
        
        JOptionPane.showMessageDialog(null,"No Data To Delete",
                "Hotel Management System",JOptionPane.OK_OPTION);
        }else{
         JOptionPane.showMessageDialog(null,"Select A Row To Delete",
                "Hotel Management System",JOptionPane.OK_OPTION);
   }
}else{
    MOdel.removeRow(JTable1.getSelectedRow());
}
    }//GEN-LAST:event_DeleteActionPerformed

    private void ResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResetActionPerformed
      DefaultTableModel MOdel = (DefaultTableModel) JTable1.getModel();
      MOdel.setRowCount(0);
      jtxtCustomerRef.setText(null);
     jtxtFirst.setText(null);
     jtxtLast.setText(null);
     jtxtAddress1.setText(null);
        jtxtPostCode.setText(null);
        jtxtCustMob.setText(null);
        jtxtEmail.setText(null);
        jtxtNationality.setText(null);
        jDateChooser1.setDate(null);
        jLocaleChooser1.setSelectedIndex(0);
        jtxtGender.setSelectedIndex(0);
        jDateChooser2.setDate(null);
        jDateChooser2.setDate(null);
        jcobMeal.setSelectedIndex(0);
        jtxtRoomType.setSelectedIndex(0);
        jtxtRoomNo.setSelectedIndex(0);
        jtxtRoomExtNo.setSelectedIndex(0);
        

        
        
        
    }//GEN-LAST:event_ResetActionPerformed
private JFrame frame;
    private void jtxtPostCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtPostCodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtPostCodeActionPerformed

    private void jtxtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtEmailActionPerformed

    private void jtxtNationalityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtNationalityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtNationalityActionPerformed

    private void UpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateActionPerformed
 DefaultTableModel MOdel=(DefaultTableModel) JTable1.getModel();
if(JTable1.getSelectedRow() == -1){
   if(JTable1.getRowCount() == 0){
       JOptionPane.showMessageDialog(null,"Hotel Booking Update Confirm","Hotel Management System",
               JOptionPane.OK_OPTION);
   } 
}
    }//GEN-LAST:event_UpdateActionPerformed

    private void TotalcostActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TotalcostActionPerformed
       
        Connection con= null;
       Statement sta =null;
        try{
          con = DriverManager.getConnection("jdbc:mysql://localhost:3306/hotel","root","");
          sta= con.createStatement();//for running og query
           String query=("Insert into hotelm (CustomerRef,FirstName,LastName,Address,Postcode,CustomerMob,Email,Nationality,DOB,Gender,CheckInDate,CheckOutDate,Meal,RoomNo,RoomType)"+ "values('"+jtxtCustomerRef.getText()+"',"+ "'"+jtxtFirst.getText()+"',"+ "'"+jtxtLast.getText()+"',"+ "'"+jtxtAddress1.getText()+"',"+ "'"+jtxtPostCode.getText()+"',"+ "'"+jtxtCustMob.getText()+"',"+ "'"+jtxtEmail.getText()+"',"+ "'"+jtxtNationality.getText()+"',"+ "'"+jDateChooser1.getDate()+"',"+ "'"+jtxtGender.getSelectedIndex()+"',"+ "'"+jDateChooser2.getDate()+"',"+ "'"+jDateChooser3.getDate()+"',"+ "'"+jcobMeal.getSelectedIndex()+"',"+ "'"+jtxtRoomNo.getSelectedIndex()+"',"+ "'"+jtxtRoomType.getSelectedIndex()+"')");
            //System.out.println(query);
          sta.executeUpdate(query);
          JOptionPane.showMessageDialog(null, "Query Executed");
        }catch(Exception ex){
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
        int SingleRoom= 700;
        int DoubleRoom= 1000;
        int FamilyRoom= 1200;
        
        int oneMeal = 100;
        int twoMeals= 200;
        int threeMeals= 300;
        //int fourMeals=400;
        SimpleDateFormat  format=new SimpleDateFormat("yyyy-MM-dd");
        Date Check_In_Date = null;
        Date Check_Out_Date = null;
        try{  
            Check_In_Date=format.parse(format.format(jDateChooser2.getDate()));
            System.out.println(Check_In_Date); 
            Check_Out_Date=format.parse(format.format(jDateChooser3.getDate()));
            System.out.println(Check_Out_Date);
                     
        }
        catch(ParseException e){
            e.printStackTrace();
        }
        long Checkdiff=  Check_Out_Date.getTime()- Check_In_Date.getTime();
        //System.out.println(Checkdiff);
        int Daysdiff = (int)(Checkdiff /1000/60/60/24);
        
        if(jtxtRoomType.getSelectedItem().equals("Single") && jcobMeal.getSelectedItem().equals("1 Item") )
        {//System.out.println(Daysdiff);
            jtxtTotal.setText(Integer.toString(Daysdiff *SingleRoom + oneMeal));
            jtxtTax.setText(Integer.toString(Daysdiff *SingleRoom + oneMeal));
 jtxtSubTotal.setText(Integer.toString(Daysdiff *SingleRoom + oneMeal));       
            
        double q=Double.parseDouble(jtxtTax.getText());
        //System.out.println(q);
        q= (q*0.25)/100;
        String tax=String.format(("Rs %.2f"),q);
        jtxtTax.setText(tax);
           // System.out.println(q);
        double st=Double.parseDouble(jtxtSubTotal.getText());
         //st=(st);
         String subtotal=String.format(("Rs %.2f "),st);
        jtxtSubTotal.setText(subtotal);
            //System.out.println(st);
        Double tt=Double.parseDouble(jtxtTotal.getText());
       // tt=(tt);
        String total=String.format(("Rs %.2f"),tt+q);
        jtxtTotal.setText(total);
            //System.out.println(tt+q);
        }     
//===================================================================================== 
        else if(jtxtRoomType.getSelectedItem().equals("Double") && jcobMeal.getSelectedItem().equals("1 Item") )
        {
            jtxtTotal.setText(Integer.toString(Daysdiff *DoubleRoom + oneMeal));
            jtxtTax.setText(Integer.toString(Daysdiff *DoubleRoom + oneMeal));
 jtxtSubTotal.setText(Integer.toString(Daysdiff *DoubleRoom + oneMeal));       
        
        double q=Double.parseDouble(jtxtTax.getText());
        q= (q*0.25)/100;
        String tax=String.format(("Rs %.2f"),q);
        jtxtTax.setText(tax);
        double st=Double.parseDouble(jtxtSubTotal.getText());
         st=(st);
         String subtotal=String.format(("Rs %.2f"),st);
        jtxtSubTotal.setText(subtotal);
        Double tt=Double.parseDouble(jtxtTotal.getText());
        tt=(tt);
        String total=String.format(("Rs %.2f"),tt+q);
        jtxtTotal.setText(total);
        }   
        
        
        else if(jtxtRoomType.getSelectedItem().equals("family") && jcobMeal.getSelectedItem().equals("1 Item") )
        {
            jtxtTotal.setText(Integer.toString(Daysdiff *FamilyRoom + oneMeal));
            jtxtTax.setText(Integer.toString(Daysdiff *FamilyRoom + oneMeal));
 jtxtSubTotal.setText(Integer.toString(Daysdiff *FamilyRoom + oneMeal));       
        
        double q=Double.parseDouble(jtxtTax.getText());
        q= (q*0.25)/100;
        String tax=String.format(("Rs %.2f"),q);
        jtxtTax.setText(tax);
        double st=Double.parseDouble(jtxtSubTotal.getText());
         st=(st);
         String subtotal=String.format(("Rs %.2f"),st);
        jtxtSubTotal.setText(subtotal);
        Double tt=Double.parseDouble(jtxtTotal.getText());
        tt=(tt);
        String total=String.format(("Rs %.2f"),tt+q);
        jtxtTotal.setText(total);
        }     
   //====================================================================================
   if(jtxtRoomType.getSelectedItem().equals("Single") && jcobMeal.getSelectedItem().equals("2 Item") )
        {
           // System.out.println(Daysdiff);
            //System.out.println(SingleRoom);
            //System.out.println(twoMeals);
            jtxtTotal.setText(Integer.toString(Daysdiff *SingleRoom + twoMeals));
            jtxtTax.setText(Integer.toString(Daysdiff *SingleRoom + twoMeals));
 jtxtSubTotal.setText(Integer.toString(Daysdiff *SingleRoom + twoMeals));       
          
        double q=Double.parseDouble(jtxtTax.getText());
        
        q= (q*0.25)/100;
        String tax=String.format(("Rs %.2f"),q);
        jtxtTax.setText(tax);
        double st=Double.parseDouble(jtxtSubTotal.getText());
         st=(st);
            System.out.println(st);  
         String subtotal=String.format(("Rs %.2f"),st);
        jtxtSubTotal.setText(subtotal);
        Double tt=Double.parseDouble(jtxtTotal.getText());
        tt=(tt);
        String total=String.format(("Rs %.2f"),tt+q);
        jtxtTotal.setText(total);
        }    
   
   else if(jtxtRoomType.getSelectedItem().equals("Double") && jcobMeal.getSelectedItem().equals("2 Item") )
        {
            jtxtTotal.setText(Integer.toString(Daysdiff *DoubleRoom + twoMeals));
            jtxtTax.setText(Integer.toString(Daysdiff *DoubleRoom + twoMeals));
 jtxtSubTotal.setText(Integer.toString(Daysdiff *DoubleRoom + twoMeals));       
        
        double q=Double.parseDouble(jtxtTax.getText());
        q= (q*0.25)/100;
        String tax=String.format(("Rs %.2f"),q);
        jtxtTax.setText(tax);
        double st=Double.parseDouble(jtxtSubTotal.getText());
         st=(st);
         String subtotal=String.format(("Rs %.2f"),st);
        jtxtSubTotal.setText(subtotal);
        Double tt=Double.parseDouble(jtxtTotal.getText());
        tt=(tt);
        String total=String.format(("Rs %.2f"),tt+q);
        jtxtTotal.setText(total);
        }     
   
   else if(jtxtRoomType.getSelectedItem().equals("Family") && jcobMeal.getSelectedItem().equals("2Item") )
        {
            jtxtTotal.setText(Integer.toString(Daysdiff *FamilyRoom + twoMeals));
            jtxtTax.setText(Integer.toString(Daysdiff *FamilyRoom + twoMeals));
 jtxtSubTotal.setText(Integer.toString(Daysdiff *FamilyRoom + twoMeals));       
        
        double q=Double.parseDouble(jtxtTax.getText());
        q= (q*0.25)/100;
        String tax=String.format(("Rs %.2f"),q);
        jtxtTax.setText(tax);
        double st=Double.parseDouble(jtxtSubTotal.getText());
         st=(st);
         String subtotal=String.format(("Rs %.2f"),st);
        jtxtSubTotal.setText(subtotal);
        Double tt=Double.parseDouble(jtxtTotal.getText());
        tt=(tt);
        String total=String.format(("Rs %.2f"),tt+q);
        jtxtTotal.setText(total);
        }     
   //===================================================================================
   if(jtxtRoomType.getSelectedItem().equals("Single") && jcobMeal.getSelectedItem().equals("3 Item") )
        {
            jtxtTotal.setText(Integer.toString(Daysdiff *SingleRoom + threeMeals));
            jtxtTax.setText(Integer.toString(Daysdiff *SingleRoom + threeMeals));
 jtxtSubTotal.setText(Integer.toString(Daysdiff *SingleRoom + threeMeals));       
        
        double q=Double.parseDouble(jtxtTax.getText());
        q= (q*0.25)/100;
        String tax=String.format(("Rs %.2f"),q);
        jtxtTax.setText(tax);
        double st=Double.parseDouble(jtxtSubTotal.getText());
         st=(st);
         String subtotal=String.format(("Rs %.2f"),st);
        jtxtSubTotal.setText(subtotal);
        Double tt=Double.parseDouble(jtxtTotal.getText());
        tt=(tt);
        String total=String.format(("Rs %.2f"),tt+q);
        jtxtTotal.setText(total);
        }     
   else if(jtxtRoomType.getSelectedItem().equals("Double") && jcobMeal.getSelectedItem().equals("3 Item") )
        {
            jtxtTotal.setText(Integer.toString(Daysdiff *DoubleRoom + threeMeals));
            jtxtTax.setText(Integer.toString(Daysdiff *DoubleRoom + threeMeals));
 jtxtSubTotal.setText(Integer.toString(Daysdiff *DoubleRoom + threeMeals));       
        
        double q=Double.parseDouble(jtxtTax.getText());
        q= (q*0.25)/100;
        String tax=String.format(("Rs %.2f"),q);
        jtxtTax.setText(tax);
        double st=Double.parseDouble(jtxtSubTotal.getText());
         st=(st);
         String subtotal=String.format(("Rs %.2f"),st);
        jtxtSubTotal.setText(subtotal);
        Double tt=Double.parseDouble(jtxtTotal.getText());
        tt=(tt);
        String total=String.format(("Rs %.2f"),tt+q);
        jtxtTotal.setText(total);
        }     
   
  else if(jtxtRoomType.getSelectedItem().equals("Family") && jcobMeal.getSelectedItem().equals("3 Item") )
        {
            jtxtTotal.setText(Integer.toString(Daysdiff *FamilyRoom + threeMeals));
            jtxtTax.setText(Integer.toString(Daysdiff *FamilyRoom + threeMeals));
 jtxtSubTotal.setText(Integer.toString(Daysdiff *FamilyRoom + threeMeals));       
        
        double q=Double.parseDouble(jtxtTax.getText());
        q= (q*0.25)/100;
        String tax=String.format(("Rs %.2f"),q);
        jtxtTax.setText(tax);
        double st=Double.parseDouble(jtxtSubTotal.getText());
         st=(st);
         String subtotal=String.format(("Rs %.2f"),st);
        jtxtSubTotal.setText(subtotal);
        Double tt=Double.parseDouble(jtxtTotal.getText());
        tt=(tt);
        String total=String.format(("Rs %.2f"),tt+q);
        jtxtTotal.setText(total);
        }     
//=====================================================================================
          DefaultTableModel MOdel = (DefaultTableModel) JTable1.getModel();
      MOdel.addRow(new Object[]{
      jtxtCustomerRef.getText(),
     jtxtFirst.getText(),
     jtxtLast.getText(),
     jtxtAddress1.getText(),
        jtxtPostCode.getText(),
        jtxtCustMob.getText(),
        jtxtEmail.getText(),
        jtxtNationality.getText(),
        jDateChooser1.getDate(),
        jLocaleChooser1.getSelectedItem(),
        jtxtGender.getSelectedItem(),
        jDateChooser2.getDate(),
        jDateChooser3.getDate(),
        jcobMeal.getSelectedItem(),
        jtxtRoomType.getSelectedItem(),
        jtxtRoomNo.getSelectedItem(),
        jtxtRoomExtNo.getSelectedItem(),
        
        
        
         
      });
       
    }//GEN-LAST:event_TotalcostActionPerformed

    private void Exit1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Exit1ActionPerformed
    frame = new JFrame("Exit");
    if (JOptionPane.showConfirmDialog(frame,"Confirm If You Want to Exit","Hotel Management System",
            JOptionPane.YES_NO_OPTION) ==JOptionPane.YES_NO_OPTION);{
         System.exit(0);
       }
    
    }//GEN-LAST:event_Exit1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
Frame fr=new Frame();
fr.setVisible(true);

    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(hotelmanagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(hotelmanagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(hotelmanagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(hotelmanagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new hotelmanagement().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CheckIn;
    private javax.swing.JLabel CheckOut;
    private javax.swing.JButton Delete;
    private javax.swing.JButton Exit1;
    private javax.swing.JTable JTable1;
    private javax.swing.JLabel Meal;
    private javax.swing.JButton Reset;
    private javax.swing.JLabel RoomType;
    private javax.swing.JButton Totalcost;
    private javax.swing.JButton Update;
    private javax.swing.JButton jButton1;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private com.toedter.calendar.JDateChooser jDateChooser3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JComboBox<String> jLocaleChooser1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField18;
    private javax.swing.JComboBox<String> jcobMeal;
    private javax.swing.JTextField jtxtAddress1;
    private javax.swing.JTextField jtxtCustMob;
    private javax.swing.JTextField jtxtCustomerRef;
    private javax.swing.JTextField jtxtEmail;
    private javax.swing.JTextField jtxtFirst;
    private javax.swing.JComboBox<String> jtxtGender;
    private javax.swing.JTextField jtxtLast;
    private javax.swing.JTextField jtxtNationality;
    private javax.swing.JTextField jtxtPostCode;
    private javax.swing.JComboBox<String> jtxtRoomExtNo;
    private javax.swing.JComboBox<String> jtxtRoomNo;
    private javax.swing.JComboBox<String> jtxtRoomType;
    private javax.swing.JTextField jtxtSubTotal;
    private javax.swing.JTextField jtxtTax;
    private javax.swing.JTextField jtxtTotal;
    // End of variables declaration//GEN-END:variables

    private static class jtxtLastName {

        private static void setText(String anull) {
            throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        }

        public jtxtLastName() {
        }
    }
}
